# Generated by Django 4.1.4 on 2023-04-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='random_location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
