# Generated by Django 4.1.4 on 2023-04-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='last_score',
            field=models.IntegerField(default=0),
        ),
    ]
