# Generated by Django 4.1.4 on 2023-04-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_score_last_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
    ]
