# Generated by Django 4.1.4 on 2023-04-22 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_score_login_date_alter_leaderboard_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='login_date',
        ),
    ]
