# Generated by Django 4.1.4 on 2023-04-22 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_score_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
