# Generated by Django 4.1.4 on 2023-04-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_score_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
