# Generated by Django 4.1.4 on 2023-04-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_score_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='score',
            name='lowest_score',
            field=models.IntegerField(default=0),
        ),
    ]
