# Generated by Django 4.1.4 on 2023-04-25 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_thanksherring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thanksherring',
            name='hello',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.leaderboard'),
        ),
    ]
