# Generated by Django 4.1.4 on 2023-04-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_thanksherring_hello'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThanksHerring',
        ),
    ]
