# Generated by Django 4.1.4 on 2023-04-25 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_delete_thanksherring'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanksHerring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.leaderboard')),
            ],
        ),
    ]
